pull_request_rules:
  - name: Auto-merge for dependency bump pull requests
    conditions:
      - or:
        - author=dependabot[bot]
        - author=github-actions[bot]
      - label=dependencies

      - check-success=Build and Test
      - check-success=Format
      - check-success=Clippy
    actions:
      merge:
        method: squash
      delete_head_branch:
