pull_request_rules:
  - name: Auto-merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Build and Test
      - check-success=Format
      - check-success=Clippy
    actions:
      merge:
        method: squash
