name: Flake

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeterminateSystems/nix-installer-action@v1

      - uses: DeterminateSystems/update-flake-lock@v3
        with:
          token: ${{ secrets.GH_PAT }}
          commit-msg: 'flake: update inputs'
          pr-title: 'flake: update inputs'
          pr-labels: 'dependencies'
